<a href="https://colab.research.google.com/github/lochanayeluri/nasscom_lab/blob/main/Nasscom_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
a = np.array((1.9,2,3))
print(a)
print(a.dtype)# even 1 element data is changed all the elements in the array changes
print(a.shape)

[1.9 2.  3. ]
float64
(3,)


In [ ]:
#2d array
b = np.array([[1,2,5,4],[4,5,8,1],[2,8,5,7]])
print(b)
print(b.ndim)# dimension
print(b.shape)#shape

[[1 2 5 4]
 [4 5 8 1]
 [2 8 5 7]]
2
(3, 4)


In [ ]:
#3D array
c = np.array([[[1,2],[5,8],[7,0]]])
print(c)
print(c.shape)
print(c.ndim)

[[[1 2]
  [5 8]
  [7 0]]]
(1, 3, 2)
3


In [ ]:
#Linear algebra
A = np.array([[1,2],[3,4]])
B = np.array([5,6])
X = np.linalg.solve(A,B)
print(X)

[-4.   4.5]


In [ ]:
#accessing
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("5th element on 2nd row : ",arr[1,4]) #indexing
print("2nd element from 2nd dimension: ",arr[-2,-1])  # negative indexing

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd row :  10
2nd element from 2nd dimension:  5


In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0,1,2])  # indexing for 3Dim array
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
3


In [ ]:
# copy --by using copy we can't make the recent updates for the copied list(x) --
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# VIEW --- by using view the copied array can take updates made on original array ---
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#Reshaping of arrays
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.shape)
print(arr)
newarr = arr.reshape(2,5)
print(newarr)

(10,)
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# indexing & slicing
data = np.array([
    [25, 50000, 0],   # age, income, defaulted?
    [40, 80000, 0],
    [22, 20000, 1],
    [35, 60000, 0],
    [29, 15000, 1]
])

print('First row:', data[0])
print('First 3 rows:\n', data[0:3])
print('All rows, first column (age):', data[:,0])
print('All rows, last column (target y):', data[:, -1])
X = data[:, :-1]
y = data[:, -1]
print('\nX (features):\n', X)
print('y (target):', y)

First row: [   25 50000     0]
First 3 rows:
 [[   25 50000     0]
 [   40 80000     0]
 [   22 20000     1]]
All rows, first column (age): [25 40 22 35 29]
All rows, last column (target y): [0 0 1 0 1]

X (features):
 [[   25 50000]
 [   40 80000]
 [   22 20000]
 [   35 60000]
 [   29 15000]]
y (target): [0 0 1 0 1]
