<a href="https://colab.research.google.com/github/lochanayeluri/nasscom_lab/blob/main/NumPy_Practice_Ex_lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice Exercises

Solve each question in the code cell below it. Do not just re-run the lab examples — use **different numbers/data** than what was shown in class so you are actually writing the logic yourself.

Run each cell with **Shift + Enter** and check that your output makes sense before moving to the next question.

### Q1. Creating a 1-D array
Create a 1-D NumPy array containing 6 numbers of your choice. Print the array and print its type using `type()`.

In [ ]:
# Write your code here
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr1))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


### Q2. Creating a 2-D array
Create a 2-D NumPy array with 3 rows and 2 columns (any numbers). Print the array.

In [ ]:
# Write your code here
import numpy as np
arr2 = np.array([[1,2],[3,4],[5,6]])
print(arr2)

[[1 2]
 [3 4]
 [5 6]]


### Q3. Creating a 3-D array
Create a 3-D NumPy array made up of two 2x3 matrices (2 blocks, each with 2 rows and 3 columns). Print the array.

In [ ]:
# Write your code here
import numpy as np
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Q4. Checking the number of dimensions
Using the three arrays you created in Q1, Q2, and Q3, print the number of dimensions of each using the `.ndim` attribute.

In [ ]:
# Write your code here
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


### Q5. Accessing elements with indexing
Create a 2-D array with 2 rows and 5 columns of your own numbers.
1. Print the 3rd element of the 1st row using positive indexing.
2. Print the last element of the 2nd row using **negative** indexing.

In [ ]:
# Write your code here
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr)
print("3rd element of the 1st row : ",arr[0,2])
print("last element of the 2nd row  : ",arr[-1,-1])

[[1 2 3 4 5]
 [6 7 8 9 0]]
3rd element of the 1st row :  3
last element of the 2nd row  :  0


### Q6. Accessing elements in a 3-D array
Using the 3-D array you created in Q3, access and print one specific element using three indices, e.g. `arr[block, row, col]`.

In [ ]:
# Write your code here
print(arr3)
print("second element in first row first block : ",arr3[0,0,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
second element in first row first block :  2


### Q7. Checking data type
Create one NumPy array of integers and one NumPy array that contains at least one decimal number. Print the `.dtype` of each and explain in a comment why they are different.

In [ ]:
# Write your code here
print(arr1)
float_arr = np.array([9,2,0.7,4.8,5,1])
print(float_arr)
print(arr1.dtype)
print(float_arr.dtype)
#the first array consists of whole numbers while the second array consists of whole numbers and decimals so it is float data type

[1 2 3 4 5 6]
[9.  2.  0.7 4.8 5.  1. ]
int64
float64


### Q8. Copy vs View
Create a 1-D array. Make a **copy** of it using `.copy()` and a **view** of it using `.view()`. Change the first element of the original array, then print the original array, the copy, and the view. In a comment, explain what you observe and why.

In [ ]:
# Write your code here
print(arr1)
copy_arr1= arr1.copy()
view_arr1= arr1.view()
arr1[0]=6
print(arr1)
print(copy_arr1)
print(view_arr1)
# By using COPY we can only create a copy of the array the changes after copying is not modified while in VIEW the array will update the changes also.

[1 2 3 4 5 6]
[6 2 3 4 5 6]
[1 2 3 4 5 6]
[6 2 3 4 5 6]


### Q9. Shape of an array
1. Create a 2-D array with 3 rows and 4 columns and print its `.shape`.
2. Create a 1-D array of 4 numbers with `ndmin=5` and print both the array and its shape.

In [ ]:
# Write your code here
arr2 = np.array([[1,2,3,4],[5,6,7,8],[0,9,8,7]])
print(arr2)
print(arr2.shape)
arr1 = np.array([1,2,3,4],ndmin=5)
print(arr1)
print(arr1.shape)

[[1 2 3 4]
 [5 6 7 8]
 [0 9 8 7]]
(3, 4)
[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


### Q10. Reshaping arrays
Create a 1-D array with 15 elements. Reshape it into a 2-D array with 3 rows and 5 columns using `.reshape()`. Print the result.

In [ ]:
# Write your code here
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(arr1.shape)
print(arr1)
new_arr= arr1.reshape(3,5)
print(new_arr)
print(new_arr.shape)

(15,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)


### Q11. Linear algebra with NumPy
Solve the following system of equations using `np.linalg.solve()`:

2x + y = 11

x + 3y = 18

Print the values of x and y.

In [ ]:
# Write your code here
A = np.array([[2,1],[1,3]])
B = np.array([11,18])
X = np.linalg.solve(A,B)
print(X)

[3. 5.]


### Q12. arange, zeros, and ones
1. Use `np.zeros()` to create a 4x2 array of zeros.
2. Use `np.ones()` to create a 3x3 array of ones.
3. Use `np.arange()` to create an array of numbers from 5 to 30 with a step of 5.

Print all three.

In [ ]:
# Write your code here
zero_arr = np.zeros((4,2))
ones_arr = np.ones((3,3))
num_arr = np.arange(5,31,5)
print(zero_arr)
print(ones_arr)
print(num_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 5 10 15 20 25 30]


### Q13. Why NumPy is faster than plain Python
Create two Python lists of 500,000 numbers each. Time how long it takes to add them element-by-element using a Python loop (or list comprehension). Then convert both lists to NumPy arrays and time how long it takes to add them using `+`. Print both times and, in a comment, state which was faster and roughly by how much.

In [ ]:
# Write your code here
import numpy as np
import time
list1 = list(range(500000))
list2 = list(range(500000))
start = time.time()
result_list = [a + b for a, b in zip(list1, list2)]  # Python list addition
python_time = time.time() - start
arr1 = np.array(list1)  # Convert to NumPy arrays
arr2 = np.array(list2)
start = time.time()  # NumPy addition
result_numpy = arr1 + arr2
numpy_time = time.time() - start
print("Python time:", python_time)
print("NumPy time:", numpy_time)
# NumPy is faster because it uses optimized array operations.

Python time: 0.045188188552856445
NumPy time: 0.0038080215454101562


### Q14. Vectors vs matrices
Create a 1-D NumPy array representing a single customer's features: `[height_cm, weight_kg, age]` (make up your own values). Then create a 2-D NumPy array representing 4 different customers with the same 3 features each. Print the `.shape` and `.ndim` of both arrays.

In [ ]:
# Write your code here
import numpy as np
# 1-D array for one customer
customer = np.array([170, 65, 20])
# 2-D array for 4 customers
customers = np.array([[170, 65, 20],[165, 58, 22],[175, 72, 25],[168, 60, 21]])
print("Customer:", customer)
print("Shape:", customer.shape)
print("Dimensions:", customer.ndim)
print("\nCustomers:")
print(customers)
print("Shape:", customers.shape)
print("Dimensions:", customers.ndim)

Customer: [170  65  20]
Shape: (3,)
Dimensions: 1

Customers:
[[170  65  20]
 [165  58  22]
 [175  72  25]
 [168  60  21]]
Shape: (4, 3)
Dimensions: 2


### Q15. Indexing and slicing to build X and y
Create a 2-D array with 6 rows and 3 columns, where the last column is a target label (0 or 1) and the first two columns are features (make up your own numbers).
1. Print the first 3 rows only.
2. Print only the first column, for all rows.
3. Split the array into `X` (all columns except the last) and `y` (only the last column), and print both.

In [ ]:
# Write your code here
import numpy as np
arr = np.array([[10, 20, 0],[15, 25, 1],[30, 40, 1],[12, 18, 0],[35, 45, 1],[22, 28, 0]])
# 1. Print the first 3 rows
print("First 3 rows:")
print(arr[:3])
# 2. Print the first column
print("First column:")
print(arr[:, 0])
# 3. Split into X and y
X = arr[:, :-1]
y = arr[:, -1]
print("X:")
print(X)
print("y:")
print(y)

First 3 rows:
[[10 20  0]
 [15 25  1]
 [30 40  1]]
First column:
[10 15 30 12 35 22]
X:
[[10 20]
 [15 25]
 [30 40]
 [12 18]
 [35 45]
 [22 28]]
y:
[0 1 1 0 1 0]


### Q16. Vectorized operations and boolean masking
Create a 1-D NumPy array of 8 exam scores (0-100) of your choice. Without using any loop:
1. Add 5 bonus marks to every score and print the result.
2. Print a boolean array showing which scores are 50 or above.
3. Print only the scores that are 50 or above using boolean masking.

In [ ]:
# Write your code here
import numpy as np
scores = np.array([45, 67, 82, 39, 55, 91, 48, 73])
# 1. Add 5 bonus marks
bonus_scores = scores + 5
print("Scores after bonus:")
print(bonus_scores)
# 2. Boolean array for scores 50 or above
mask = scores >= 50
print("Boolean array:")
print(mask)
# 3. Print scores 50 or above
print("Scores 50 or above:")
print(scores[mask])

Scores after bonus:
[50 72 87 44 60 96 53 78]
Boolean array:
[False  True  True False  True  True False  True]
Scores 50 or above:
[67 82 55 91 73]
